image: gradle:7.4.2

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  script: gradle --build-cache assemble --warning-mode summary --scan
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - ./core/build
      - ./desktop/build
      - .gradle

Unit-Tests:
  stage: test
  script: 
    - gradle :core:test
    - gradle clean :core:test

Check:
  stage: test
  script:  gradle clean check
  artifacts:
    paths:
      - "./core/build/reports/tests/test/*"
    expire_in: 30 days

Deploy:
  stage: deploy
  script:  gradle clean desktop:dist
  artifacts:
    paths:
      - "./desktop/build/libs/*"
  only:
    - main
    - merge_requests
